version: 2.1
orbs:
  cypress: cypress-io/cypress@3
  SlackNotifier: svinstech/slack-notifier-orb@1

jobs:
  send-message:
    docker:
      - image: cimg/base:current
    steps:
      - SlackNotifier/send-slack-message:
          header: Test message
          message: "Here is a variable value: ${KELLEN_KINCAID_SLACK_WEBHOOK}"
          channelWebhookEnvironmentVariables: KELLEN_KINCAID_SLACK_WEBHOOK

############


executor: cypress/default

commands:
  slack-reporter:
    steps:
      - run:
          name: Slack - Setting Failure Condition
          command: |
            echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
          when: on_fail
      - run:
          name: Slack - Setting Success Condition
          command: |
            echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
          when: on_success
      - run:
          name: Slack - Sending Status Alert
          shell: /bin/bash
          when: always
          command: |
            sh ./.circleci/utilities/send_build_status_to_slack.sh
          no_output_timeout: 15m

qa-workflow: &qa-workflow
  jobs:
    - cypress/run:
        # install-browsers: true # Installs Chrome & Firefox at runtime
        package-manager: yarn
        cypress-command: 'yarn cypress run'
        name: "MarketingQA Publish_Site Tests"
        post-steps:
          - slack-reporter

workflows:
  test-sending-messages:
    jobs:
      - send-message
  qa:
    <<: *qa-workflow