version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

#executors:
#  with-chrome:
#    docker:
#      - image: 'cypress/browsers:node16.16.0-chrome107-ff107'

commands:
  slack-reporter:
    steps:
      - run:
          name: Slack - Setting Failure Condition
          command: |
            echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
          when: on_fail
      - run:
          name: Slack - Setting Success Condition
          command: |
            echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
          when: on_success
      - run:
          name: Slack - Sending Status Alert
          shell: /bin/bash
          when: always
          command: |
            ./.circleci/utilities/send_build_status_to_slack.sh
          no_output_timeout: 15m

qa-workflow: &qa-workflow
  jobs:
#    - cypress/install:
    - cypress/run:
#        requires:
#          - cypress/install
        name: "MarketingQA Publish_Site Tests"
        executor: cypress-io/base-14
        browser: chrome
        spec: ./cypress/integration/*
        no-workspace: true
        yarn: true
        post-steps:
          - slack-reporter

workflows:
  qa:
    <<: *qa-workflow